# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-01-28 14:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Fournisseur',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100, null=True)),
                ('prenom', models.CharField(max_length=100, null=True)),
                ('tel', models.CharField(max_length=15, null=True)),
                ('adresse', models.CharField(max_length=250, null=True)),
                ('souscrit', models.BooleanField(default=True)),
            ],
        ),
    ]
