# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-03-30 16:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_auto_20170309_2039'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collection',
            name='title',
            field=models.CharField(blank=True, choices=[('MANDEO', 'mandeo'), ('WAXSHOP', 'waxshop'), ('SAPHIR', 'saphir'), ('YVES ROCHER', 'yvesrocher')], max_length=20, null=True),
        ),
    ]
